language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=travis
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 #give xvfb some time to start
services:
  - mongodb
notifications:
  email:
   recipients:
    - joebm08@gmail.com
    - treyqg15@gmail.com
   on_success: always
   on_failure: always