language: node_js
node_js:
  - "0.10"
install:
  - "npm install"
before_script:
  - "npm install -g grunt-cli"
script:
  - "grunt test"
env:
  - NODE_ENV=travis
services:
  - mongodb
notifications:
  email:
   recipients:
    - joebm08@gmail.com
    - treyqg15@gmail.com
   on_success: always
   on_failure: always