language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=travis
install:
  - sudo apt-get update
  - sudo apt-get install chromium-browser
  - npm install
services:
  - mongodb
notifications:
  email:
   recipients:
    - joebm08@gmail.com
    - treyqg15@gmail.com
   on_success: always
   on_failure: always