--- 
env: 
  - NODE_ENV=travis
language: node_js
node_js: 
  - "0.10"
notifications: 
  email: 
    recipients: 
      - joebm08@gmail.com
      - treyqg15@gmail.com
  on_failure: always
  on_success: always
services: 
  - mongodb
