language: node_js
node_js:
  - "0.10"
services:
  - mongodb
env:
   - NODE_ENV=travis
notifications:
  email:
   recipients:
    - joebm08@gmail.com
    - treyqg15@gmail.com
   on_success: always
   on_failure: always